controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    start()
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    Gun = sprites.createProjectileFromSprite(img`
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ...........a............
        ..........aaa...........
        ..........aaa...........
        ..........aaa...........
        ..........aaa...........
        ..........aaa...........
        ..........aaa...........
        ..........aaa...........
        ..........aaa...........
        ..........aaa...........
        ..........aaa...........
        ..........aca...........
        ........cccbccc.........
        ...........c............
        ...........c............
        ...........c............
        ..........ccc...........
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `, Whopper, 50, 50)
    Gun.setVelocity(0, -100)
})
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Projectile, function (sprite, otherSprite) {
    hp += -1
    pause(200)
    if (hp == 0) {
        sprites.destroy(Boss)
        pause(500)
        game.splash("" + name + " You Win!")
        pause(2000)
        game.gameOver(true)
    }
})
function EnemyBullets () {
    EnemyShots = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . b . . . . . . . 
        . . . . . . . b d b . . . . . . 
        . . . . . . . c d c . . . . . . 
        . . . . . . . c 5 c . . . . . . 
        . . . . . . c d 5 d c . . . . . 
        . . . b c c d 5 5 5 d c c b . . 
        . . b d d 5 5 5 5 5 5 5 d d b . 
        . . . b c c d 5 5 5 d c c b . . 
        . . . . . . c d 5 d c . . . . . 
        . . . . . . . c 5 c . . . . . . 
        . . . . . . . c d c . . . . . . 
        . . . . . . . b d b . . . . . . 
        . . . . . . . . b . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.Food)
    EnemyShots.setVelocity(50, 50)
    EnemyShots.setBounceOnWall(true)
    EnemyShots2 = sprites.create(img`
        ....ffffff.........ccc..
        ....ff77ccf.......cc6f..
        .....ffccccfff...cc66f..
        ....cc76667777cccc667f..
        ...c9b6677777777cc677f..
        ..c9999b777777777777fc..
        .c7b99999b777777777c77c.
        c7777b99bb7777ccccccc77f
        f777777777777c777ccfffff
        .f7777777777666777f.....
        ..ff7777777cf666777f....
        ....ffffffffff666777c...
        .........f7cfffc7777c...
        .........fcc7ffffffff...
        ..........fc7ffff.......
        ...........fffff........
        `, SpriteKind.Player)
    EnemyShots2.setVelocity(100, 20)
    EnemyShots2.setBounceOnWall(true)
}
function start () {
    hp = 1000
    Boss = sprites.create(img`
        . . . . . . 3 . 3 . . . . . . . 
        . . . . . f 3 3 3 f f . . . . . 
        . . . . f 1 3 5 3 1 5 f . . . . 
        . . . f 1 5 5 5 5 5 1 5 f . . . 
        . . . f 5 5 f f f f 5 1 f . . . 
        . . . f 5 f f d d f f 5 f . . . 
        . . f 5 f d f d d f d f 5 f . . 
        . . f 5 f d 3 d d 3 d f 5 f . . 
        . . f 5 5 f d d d d f 5 5 f . . 
        . f 5 5 f 3 f f f f 3 f 5 5 f . 
        . . f f d 3 9 3 3 9 3 d f f . . 
        . . f d d f 3 9 9 3 f d d f . . 
        . . . f f 3 3 3 3 3 3 f f . . . 
        . . . f 3 3 9 3 3 9 3 3 f . . . 
        . . . f f f f f f f f f f . . . 
        . . . . . f f . . f f . . . . . 
        `, SpriteKind.Enemy)
    Boss.setBounceOnWall(true)
    Boss.setStayInScreen(true)
    Boss.setPosition(76, 20)
    EnemyBullets()
    while (hp > 0) {
        Boss.setVelocity(randint(0, 100), randint(0, 100))
        pause(2000)
    }
}
let EnemyShots2: Sprite = null
let EnemyShots: Sprite = null
let Boss: Sprite = null
let hp = 0
let Gun: Sprite = null
let name = ""
let Whopper: Sprite = null
Whopper = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ......cccc.cccc.....
    .....ccccccccccc....
    ....ccccccccccccc...
    ....ccc8ccccc8ccc...
    ....ccccccccccccc...
    .....ccccfcfcccc....
    ......ccccfcccc.....
    .......ccccccc......
    ........ccccc.......
    .........ccc........
    ..........c.........
    ....................
    ....................
    ....................
    ....................
    `, SpriteKind.Player)
Whopper.setStayInScreen(true)
name = game.askForString("What is your name?")
controller.moveSprite(Whopper)
game.splash("PRESS B TO BEGIN")
